(function(g,l,p,n,e){g[l]=g[l]||{};for(g[l].q=g[l].q||[];e<n.length;)p(n[e++],g[l])})(window,"extole",function(g,l){l[g]=l[g]||function(){l.q.push([g,arguments])}},["log"],0);
extole.define||function(){function g(){}function l(){var m="undefined"!==typeof opera&&"[object Opera]"===opera.toString(),a=document.createElement("script");this.useInteractive=a.attachEvent&&!(a.attachEvent.toString&&0>a.attachEvent.toString().indexOf("[native code"))&&!m}var p=[],n=function(m){var a;b(p,function(d){if(c(d.url)==c(m))return a=d,!1});return a},e=function(m){extole.log("debug","[REQUIRE] "+m)},k=function(m){extole.log("error","[REQUIRE] "+m)},b=function(m,a){if(m.length)for(var d=
0;d<m.length;d++)a(m[d],d);else for(d in m)m.hasOwnProperty(d)&&a(m[d],d)},f=function(m,a){var d=[];b(m,function(m,h){d[h]=a(m,h)});return d},c=function(m){return"string"!==typeof m?m:m.match(/origin-\d/)?m.substring(m.indexOf("type=")).replace(/version=\d+:/,""):m},a=function(m){var a=m.split("/").slice(-1)[0],d=a.length;b(a.toLowerCase(),function(m){d+=" abcdefghijklmnopqrstuvwxyz1234567890-_.".indexOf(m)});return m.replace("origin","origin-"+d%8)},q=function(m){var d=!!m.match(/^extole-creatives:/),
h=!!m.match(/^extole-media:/),b=!!m.match(/^core-root:\/\//),f=!!m.match(/^extole-assets:/),c=!!m.match(/origin\./),e=!!m.match(/^http:/),w=!!m.match(/^https:/);return d?(m=m.slice(17),q("extole-assets:/core-modules/"+m)):f?(m=m.slice(14),m="extole-media:/assets/"+m,q(m)):h?(m=m.slice(13),m=extole.CORE_ROOT+m,q(m)):b?(m=m.slice(12),m=extole.CORE_ROOT+m,q(m)):c?(m=a(m),m+="?site="+window.location.hostname,q(m)):e?(m=m.slice(5),q(m)):w?(m=m.slice(6),q(m)):m};g.prototype={getUnresolvedDependencies:function(){var m=
[];b(this.dependencies,function(a){"$config"!=a&&(a=n(a),(!a||a&&!a._defined)&&m.push(a))});return m},getDependencies:function(){var a=this,d=[];b(a.dependencies,function(h){h="$config"==h?a.config||null:n(h).definition||null;d.push(h)});return d},define:function(){var a=this;a.defineStartTime=a.defineStartTime||(new Date).getTime();if(!a._defining&&!a._defined&&a.dependencies)if(a._defining=!0,0<a.getUnresolvedDependencies().length)a._defining=!1;else{var h=function(h){a.definedCallback=void 0;a.definition=
h;a.end=(new Date).getTime();a.timeToDefine=a.end-a.start;a.timeToFetch&&e("Fetched "+a.url+" in "+a.timeToFetch+"ms");a.isAsync&&e("Defined async "+a.url+" in "+a.timeToDefine+"ms");a._defining=!1;a._defined=!0;setTimeout(d,1)},b=a.getDependencies(),f={isAsync:!1,async:function(){f.isAsync=a.isAsync=!0;return function(a){h(a)}}};(function(){if(a.definedCallback){var d=a.definedCallback,d=d&&d.apply(f,b);f.isAsync||h(d)}else h(!0)})()}},fetch:function(){var a=this;a._fetching||a._fetched||(a.url?
(a._fetching=!0,a.startFetchTime=(new Date).getTime(),h.loadModule(a.url,function(){a._fetching=!1;a.endFetchTime=(new Date).getTime();a.timeToFetch=a.endFetchTime-a.startFetchTime;a._fetched=!0;a.define()})):k("Tried to fetch a module without a url - dependencies: "+a.dependencies+" definedCallback: "+(a.definedCallback?"exists":"null")+" config: "+a.config))}};l.prototype={defineQueue:[],interactiveScript:null,currentlyAddingScript:null,getInteractiveScript:function(){if(h.interactiveScript&&"interactive"==
h.interactiveScript.readyState)return h.interactiveScript;for(var a=document.getElementsByTagName("head")[0].getElementsByTagName("script"),d,b=a.length-1;0<=b;b--){var f=this.getScriptDataUrl(a[b]);a[b]&&"interactive"==a[b].readyState&&f&&(d=a[b],e("...interactive script "+d.src))}return d},scriptUrlAttributeName:"data-extole-require-url",getScriptDataUrl:function(a){return a.getAttribute(this.scriptUrlAttributeName)},setScriptDataUrl:function(a,d){a.setAttribute(this.scriptUrlAttributeName,d)},
attachOnLoad:function(a,d){d=d||function(){};var h=this.useInteractive,b="PLAYSTATION 3"===navigator.platform?/^complete$/:/^(complete|loaded)$/,f=function(q){var c=a.readyState;if(h&&"interactive"==c)interactiveScript=a;else if("load"===q.type||c.match(b))h?a.detachEvent("onreadystatechange",f):a.removeEventListener("load",f,!1),e(a.src+" finished loading"),d(q)};h?a.attachEvent("onreadystatechange",f):a.addEventListener("load",f,!1)},defineTimeout:null,addDefine:function(a){if(a.url)a.url=q(a.url);
else{e("defining anonymous module...");var d=this.currentlyAddingScript||this.getInteractiveScript();this.useInteractive&&d?(d=this.getScriptDataUrl(d),e("..scriptToCompare has data url "+d),a.url=d,this.interactiveScript=null):this.useInteractive&&e("..found no scriptToCompare")}a.dependencies=f(a.dependencies,q);this.useInteractive&&!a.url&&k("defines should not be missing a url in ie.");this.defineQueue.push(a);this.defineTimeout&&clearTimeout(this.defineTimeout);var h=this;this.defineTimeout=
setTimeout(function(){e("intakeDefines from addDefine timeout");h.intakeDefines()},1)},intakeTimeout:null,intakeDefines:function(){for(var a={},h=function(d,h){a[d]=a[d]?a[d]+","+h:h},f=[],q;q=this.defineQueue.shift();){var c=[];b(q.dependencies,function(a){a&&c.push(a)});var g=q.url&&n(q.url);q.url?g?h(q.url,"updated"):h(q.url,"created"):f.push("deps "+q.dependencies);b(c,function(a){h(a,"dependency");w(a)});w(q.url,c,q.definedCallback,q.config,q.isRequire)}var k="intakeDefines -- ";b(a,function(a,
d){k+="\n - "+d+" "+a});k+="\n -- "+f.length+" anonymous modules created";b(f,function(a){k+="\n - "+a});e(k);this.intakeTimeout&&clearTimeout(this.intakeTimeout);this.intakeTimeout=setTimeout(d,1)},loadModule:function(a,d){var h=document.createElement("script");h.async=!0;h.crossOrigin="anonymous";this.setScriptDataUrl(h,a);var b=this;e("loading module "+a);this.attachOnLoad(h,function(){if(!b.useInteractive){for(var h,f=b.defineQueue.length-1;0<=f;f--)b.defineQueue[f].url||(h&&k("Multiple anonymous modules loaded in one script - "+
a),h=b.defineQueue[f]);h?(e("assigned "+a+" to anonymous module"),h.url=a):e("module url didn't define a module - "+a)}e("intake defines from loadModule");b.intakeDefines();d&&d(null)});h.src=a;this.currentlyAddingScript=h;var f=document.getElementsByTagName("head")[0]||document.head;f?f.appendChild(h):extole.log("warn","[REQUIRE] <head> element not found on trying to load "+a);this.currentlyAddingScript=void 0}};var h=new l,d=function(){b(p,function(a){a._fetched?a._defined||a.define():a.fetch()})},
w=function(a,d,h,f,b){if("$config"!=a){var q=n(a),c=q||new g;q||p.push(c);a&&d&&(c._fetched=!0);c.start=c.start||(new Date).getTime();c.url=c.url||a;c.dependencies=c.dependencies||d;c.config=c.config||f;c.definedCallback=c.definedCallback||h;c.isRequire=c.isRequire||b}},v=function(a,d,f,b){a instanceof Array&&(b=f,f=d,d=a,a=void 0);h.addDefine({url:a,dependencies:d,definedCallback:f,config:b})};v.getModule=function(a){return n(a)};var u=0,t=function(){u++;return"anonymous_"+u};extole.define=v;extole.require=
function(a,d){h.addDefine({url:t(),dependencies:a,definedCallback:d,isRequire:!0})};extole.define("extole-require",[],function(){return{resolveUrl:q}});setTimeout(function(){var a=!1,d=[];b(p,function(h){h._defined||(a=!0);d.push({defineStartTime:h.defineStartTime,dependencies:h.dependencies,end:h.end,start:h.start,isRequire:h.isRequire,timeToDefine:h.timeToDefine,url:h.url,_defined:h._defined,_defining:h._defining,_fetched:h._fetched})});a&&extole.DUMP_REQUIRE_MODULES_ON_ERROR&&extole.log("error",
"After 7000ms there are unresolved extole-require modules.  ###"+JSON.stringify(d)+"###")},7E3)}();(function(){})();(function(g,l,p,n,e){g[l]=g[l]||{};for(g[l].q=g[l].q||[];e<n.length;)p(n[e++],g[l])})(window,"extole",function(g,l){l[g]=l[g]||function(){l.q.push([g,arguments])}},["createZone","log"],0);
(function(){var g=[{name:"Bose Branded Referral Domain",programDomain:"refer.bose.com",sitePatterns:"refer.bose.com *.bose.com\\.?$ *.extole.com bose.com *.extole.io api.extole.com".split(" "),isSecure:!0}];extole.CORE_ROOT="https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19";extole.CORE_CONFIG={backendTargetingEnabled:!0,cookieConsentEnabled:!1};extole.CLIENT_ID="2035193665";extole.BUILD_DATE="1579097831594";extole.VERSION="6.0";extole.PROGRAM=function(){var l=function(f,
b){var a=Error.call(this,f);this.name="ExtoleError";this.message=a.message;this.stack=a.stack;this.code=b};l.prototype=Error();l.prototype.constructor=l;var p=function(f,b){if(f.length)for(var a=0;a<f.length;a++)b(f[a],a);else for(a in f)f.hasOwnProperty(a)&&b(f[a],a)},n=function(b,c){var a=[];p(b,function(b){(b=c(b))&&(a[a.length]=b)});return a},e=function(b,c){c=c||[];var a=!1;p(c,function(q){(new RegExp(q.replace(/\./g,"\\.").replace(/\*/g,".*"))).test(b)&&(a=!0)});return a},k=function(b){var c=
window.location.hostname;return n(b,function(a){if(e(c,a.sitePatterns))return a})}(g),b=k[0];if(!b)throw new l("No program domain is configured for hostname: "+window.location.hostname+" unable to use Extole API","site_configuration_error");1<k.length&&extole.log("warn","Multiple programs matched hostname: "+window.location.hostname+" programs: "+JSON.stringify(k));return b}();extole.require(["https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/collection.js","https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/uri.js",
"https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/logger.js","create-zone-executor"],function(g,p,n,e){var k=function(){function a(a){var d=a[0];"function"===typeof b[d]?b[d].apply(null,a[1]):n.warn("Unable to execute method: "+d+", it is not implemented.")}for(var b={log:function(){var a=Array.prototype.slice.call(arguments),d=a[0];"function"===typeof n[d]&&n[d].apply(null,a.slice(1))},createZone:e.execute};extole.q.length;)a(extole.q.shift());extole.q.push=a},b=
function(){var a=function(a){var h={},b=/^extole_/,f=/^extole_zone_/;g.each(a,function(a,d){d.match(f)?h[d.replace(f,"")]=a:d.match(b)&&(h[d.replace(b,"")]=a)});return h}(p.deserialize(window.location.search));if(a.name){var b=a.name,h=a.element_id;delete a.name;delete a.element_id;extole.createZone({name:b,element_id:h,data:a})}},f=function(){var a;"function"===typeof window.onerror&&(a=window.onerror);window.onerror=function(b,h,d,f,c){if(a)try{a(b,h,d,f,c)}catch(e){}h=h||window.location.href||
"no_source_or_location.href";c=c&&c.stack?c.stack:"no_error.stack";var k=[],g=JSON.stringify({MESSAGE:b,SOURCE:h,LINE_NUMBER:d,COLUMN_NUMBER:f,STACK_TRACE:c},function(a,d){if(null!==d&&"object"==typeof d){if(0<=k.indexOf(d))return;k.push(d)}return d});d=extole.PROGRAM.programDomain.split(".").join("\\.");d=new RegExp("^(http|https):\\/\\/("+d+"|(([A-Za-z0-9-]{1,}\\.){1,}|)(xtlo\\.net|extole(\\.com|\\.io)))(?=(\\/|\\?|$))");((c+b).match(/extole/i)||d.test(h))&&extole.require(["https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/logger.js"],
function(a){a.error("Unhandled exception",JSON.parse(g))})}},c=function(){extole._bootstrapped=!0;f();k();b()};extole.bootstrap=c;extole._bootstrapped||c();if("undefined"!==typeof window.extoleAsyncInit)try{extoleAsyncInit()}catch(a){extole.require(["https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/logger.js"],function(b){b.error("Error executing extended core javascript. Message : "+a.message+" Stack: "+a.stack)})}})})();
extole.define("https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/JSON.js",[],function(){var g;"object"!==typeof g&&(g={});(function(){function l(a){return 10>a?"0"+a:a}function p(a){k.lastIndex=0;return k.test(a)?'"'+a.replace(k,function(a){var d=c[a];return"string"===typeof d?d:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function n(c,h){var d,e,k,g,t=b,m,r=h[c];r&&r instanceof Date&&(d=r,r=isFinite(d.valueOf())?d.getUTCFullYear()+"-"+l(d.getUTCMonth()+
1)+"-"+l(d.getUTCDate())+"T"+l(d.getUTCHours())+":"+l(d.getUTCMinutes())+":"+l(d.getUTCSeconds())+"Z":null);"function"===typeof a&&(r=a.call(h,c,r));switch(typeof r){case "string":return p(r);case "number":return isFinite(r)?String(r):"null";case "boolean":case "null":return String(r);case "object":if(!r)return"null";b+=f;m=[];if("[object Array]"===Object.prototype.toString.apply(r)){g=r.length;for(d=0;d<g;d+=1)m[d]=n(d,r)||"null";k=0===m.length?"[]":b?"[\n"+b+m.join(",\n"+b)+"\n"+t+"]":"["+m.join(",")+
"]";b=t;return k}if(a&&"object"===typeof a)for(g=a.length,d=0;d<g;d+=1)"string"===typeof a[d]&&(e=a[d],(k=n(e,r))&&m.push(p(e)+(b?": ":":")+k));else for(e in r)Object.prototype.hasOwnProperty.call(r,e)&&(k=n(e,r))&&m.push(p(e)+(b?": ":":")+k);k=0===m.length?"{}":b?"{\n"+b+m.join(",\n"+b)+"\n"+t+"}":"{"+m.join(",")+"}";b=t;return k}}var e,k,b,f,c,a;"function"!==typeof g.stringify&&(k=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
c={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},g.stringify=function(c,h,d){var e;f=b="";if("number"===typeof d)for(e=0;e<d;e+=1)f+=" ";else"string"===typeof d&&(f=d);if((a=h)&&"function"!==typeof h&&("object"!==typeof h||"number"!==typeof h.length))throw Error("JSON.stringify");return n("",{"":c})});"function"!==typeof g.parse&&(e=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,g.parse=function(a,h){function d(a,
b){var f,c,e=a[b];if(e&&"object"===typeof e)for(f in e)Object.prototype.hasOwnProperty.call(e,f)&&(c=d(e,f),void 0!==c?e[f]=c:delete e[f]);return h.call(a,b,e)}var b;a=String(a);e.lastIndex=0;e.test(a)&&(a=a.replace(e,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return b=eval("("+
a+")"),"function"===typeof h?d({"":b},""):b;throw new SyntaxError("JSON.parse");})})();return g});
extole.define("https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/collection.js",["https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/type.js"],function(g){var l=function(e,k){var b=Error.call(this,e);this.name="ExtoleError";this.message=b.message;this.stack=b.stack;this.code=k};l.prototype=Error();l.prototype.constructor=l;var p=function(e,k){var b,f;if(e.length===+e.length)for(f=0;f<e.length;f++){if(b=k(e[f],f),!1===b)return!1}else for(f in e)if(e.hasOwnProperty(f)&&
(b=k(e[f],f),!1===b))return!1};p.BREAK=!1;var n=function(e){if(!e||"object"!==typeof e&&!g.isPlainFunction(e))e={};for(var k=1;k<arguments.length;k++)if(g.isPlainObject(arguments[k]))for(var b in arguments[k]){var f=arguments[k][b];f!==e&&void 0!==f&&(g.isPlainObject(f)&&g.isPlainObject(e[b])?f=n(e[b],f):g.isArray(f)&&g.isArray(e[b])&&e[b].concat&&(f=e[b].concat(f)),e[b]=f)}return e};return{each:p,map:function(e,k){function b(a,b){c=[];p(a,function(a,d){c.push(b(a,d))})}function f(a,b){c={};p(a,function(a,
d){c[d]=b(a,d)})}var c;if(g.isArray(e))b(e,k);else if(g.isPlainObject(e))f(e,k);else throw new l(e+" argument must be type object or array","INVALID_ARGUMENT_EXCEPTION");return c},filter:function(e,k){function b(a,b){c=[];p(a,function(a,d){b(a,d)&&c.push(a)})}function f(a,b){c={};p(a,function(a,d){b(a,d)&&(c[d]=a)})}var c;if(g.isArray(e))b(e,k);else if(g.isPlainObject(e))f(e,k);else throw new l(e+" argument must be type object or array","INVALID_ARGUMENT_EXCEPTION");return c},merge:n,clone:function(e){return JSON.parse(JSON.stringify(e))},
flatten:function(e){function k(f,c){if(g.isPlainObject(f))p(f,function(a,b){var d=c.slice();d.push(b);k(a,d)});else{var a=c.join(".");b[a]=f}}if(!g.isPlainObject(e))return e;var b={};k(e,[]);return b},find:function(e,k){var b;p(e,function(f,c){if(k(f,c))return b=f,p.BREAK});return b},nashornToJs:function(e){var k=Object.prototype.toString.call(e),b,f;if("object"!==typeof e||k.match(/\[object (Object|Array|Null)\]/))return e;if(k.match(/\[object java\.util\.(HashMap|Collections\$UnmodifiableMap)\]/))for(f in b=
{},e)b[f]=e[f];else if("number"===typeof e.length)b=[],p(e,function(f,a){b[a]=f});else return e;return b}}});
extole.define("https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/cookie.js",["https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/logger.js"],function(g){function l(b){try{return decodeURIComponent(b.replace(e," "))}catch(c){return g.info("** cookie.decode ** Cookie error for: "+b,{error:c,message:c.message,stack:c.stack,cookiePart:b}),""}}function p(f){f=l(f);return 0===f.indexOf('"')?f.slice(1,-1).replace(k,'"').replace(b,"\\"):f}function n(b){if(!b||
!b.toUTCString){var c=new Date;c.setDate(c.getDate()+("number"===typeof b?b:0));return c}return b}var e=/\+/g,k=/\\"/g,b=/\\\\/g;return function(b,c,a){if(void 0!==c)return a=a||{},document.cookie=[encodeURIComponent(b),"=",encodeURIComponent(c),a.expires?"; expires="+n(a.expires).toUTCString():"",a.path?"; path="+a.path:"",a.domain?"; domain="+a.domain:"",a.secure?"; secure":""].join("");a:{c=document.cookie?document.cookie.split("; "):[];a=b?null:{};for(var e=0,h=c.length;e<h;e++){var d=c[e].split("="),
k=l(d[0]);if(!b)a[k]=p(d[1]);else if(b===k){b=p(d[1]);break a}}b=a}return b}});
extole.define("https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/dom.js",[],function(){var g={each:function(a,b){var h,d;if(a.length===+a.length)for(d=0;d<a.length;d++){if(h=b(a[d],d),!1===h)return!1}else for(d in a)if(a.hasOwnProperty(d)&&(h=b(a[d],d),!1===h))return!1},extend:function(){var a,b,h,d,f,c=arguments[0]||{},e=1,k=arguments.length,m=!1,g=this.extend;"boolean"===typeof c&&(m=c,c=arguments[1]||{},e=2);for("object"===typeof c||this.isFunction(c)||(c={});e<
k;e++)if(a=arguments[e],null!==a)for(b in a)h=c[b],d=a[b],c!==d&&(m&&d&&(this.isPlainObject(d)||(f=this.isArray(d)))?(f?(f=!1,h=h&&isArray(h)?h:[]):h=h&&isPlainObject(h)?h:{},c[b]=g(m,h,d)):void 0!==d&&(c[b]=d));return c},isFunction:function(a){return a&&"function"===typeof a&&a.call&&a.apply},isPlainObject:function(a){if("[object Object]"!==String(a)||a.nodeType||a.window&&a.window==a)return!1;try{if(a.constructor&&!a.constructor.prototype.hasOwnProperty("isPrototypeOf"))return!1}catch(b){return!1}return!0},
isArray:function(a){return a instanceof Array}};g.each.BREAK=!1;var l=function(){var a=[],b=function(d,b,h){for(var c=[],f=0;f<a.length;f++){var e=a[f];e.element==d&&e.eventType==b&&e.listener==h&&c.push({index:f,eventListener:e})}return c},h=function(a){this.originalEvent=a;this.type=a.type;this.keyCode=a.keyCode;this.target=a.srcElement?a.srcElement:a.target};h.prototype={preventDefault:function(){var a=this.originalEvent;a.preventDefault?a.preventDefault():a.returnValue=!1},stopPropagation:function(){var a=
this.originalEvent;a.stopPropagation&&a.stopPropagation();a.cancelBubble=!0}};return{addListener:function(d,c,f){if(0<b(d,c,f).length)console.warn("events.add - Listener already exists for event "+c+" on element "+d);else{var e=!d.addEventListener,k=function(a){e&&(a=window.event);return f.call(d,new h(a))};a.push({element:d,eventType:c,listener:f,listenerWrapper:k});d.addEventListener?d.addEventListener(c,k,!1):d.attachEvent("on"+c,k)}},triggerEvent:function(a,b,h){var c=document.createEvent("Event");
c.initEvent(b,!0,!1);g.extend(c,h);a.dispatchEvent(c)},removeListener:function(d,h,c){c=b(d,h,c);0>=c.length?console.warn("events.remove - Couldn't find exiting event listener for type \""+h+'" listener on element '+d):g.each(c,function(b){var c=b.index;b=b.eventListener;d.removeEventListener?d.removeEventListener(h,b.listenerWrapper,!1):d.detachEvent("on"+h,b.listenerWrapper);a.splice(c,1)})}}}(),p=function(){var a=function(a){a=a.className;var b={};if(!a)return b;g.each(a.split(" "),function(a){b[a]=
1});return b},b=function(a){var b="";g.each(a,function(a,h){b+=" "+h});return b.slice(1)};return{setAttribute:function(a,b,c){a.setAttribute(b,c);a[b]=c},getAttribute:function(a,b){return a.getAttribute(b)},addClass:function(h,d){var c=a(h);c[d]||(c[d]=1,h.className=b(c))},removeClass:function(c,d){var f=a(c);delete f[d];c.className=b(f)},getClassNames:function(a){return a.className.split(" ")}}}(),n=function(){var a=function(a){var b=document.createDocumentFragment(),c=document.createElement("div");
c.innerHTML=a;g.each(c.childNodes,function(a){1==a.nodeType&&b.appendChild(a)});return b},b=function(a){var b;g.each(a.childNodes,function(a){if(!b&&1==a.nodeType)return b=a,g.each.BREAK});return b};return{prepend:function(c,d){var f=b(c),e=d;"string"==typeof d&&(e=a(d));f?c.insertBefore(e,f):c.appendChild(e)},append:function(b,d){var c=d;"string"==typeof d&&(c=a(d));b.appendChild(c)}}}(),e=function(a,b){return(b||document).querySelectorAll(a)},k=function(a,b){return e(a,b)[0]},b={},f=function(a,
f){function h(){f&&(f(d),f=!1,c.removeEventListener(d,"load",h))}if(b[a]||!a)return f(b[a]),b[a]||null;var d=b[a]=document.createElement("link");c.setAttribute(d,"rel","stylesheet");c.setAttribute(d,"href",a);c.append(c.queryFirst("head"),d);c.addEventListener(d,"load",h);setTimeout(h,5E3);return d},c={addEventListener:l.addListener,removeEventListener:l.removeListener,triggerEvent:l.triggerEvent,getAttribute:p.getAttribute,setAttribute:p.setAttribute,addClass:p.addClass,removeClass:p.removeClass,
getClassNames:p.getClassNames,prepend:n.prepend,append:n.append,query:e,queryFirst:k,isVisible:function(a,b){return Boolean((k(a,b)||{}).offsetParent)},injectStylesheet:f,injectStylesheets:function(a,b){function c(a){!--d&&b&&b(e)}if(0===a.length)b();else{var d=0,e=[];g.each(a,function(a){d++;setTimeout(function(){e.push(f(a,c))},1)})}}};return c});
extole.define("https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/event-bus.js",[],function(){function g(){this._events={};var g=/\s+/,e=function(b,f,c,a){if(!c)return!0;if("object"===typeof c){for(var e in c)b[f].apply(b,[e,c[e]].concat(a));return!1}if(g.test(c)){c=c.split(g);e=0;for(var h=c.length;e<h;e++)b[f].apply(b,[c[e]].concat(a));return!1}return!0},k=function(b,f){var c,a=-1,e=b.length,h=f[0],d=f[1],k=f[2];switch(f.length){case 0:for(;++a<e;)(c=b[a]).callback.call(c.ctx);
break;case 1:for(;++a<e;)(c=b[a]).callback.call(c.ctx,h);break;case 2:for(;++a<e;)(c=b[a]).callback.call(c.ctx,h,d);break;case 3:for(;++a<e;)(c=b[a]).callback.call(c.ctx,h,d,k);break;default:for(;++a<e;)(c=b[a]).callback.apply(c.ctx,f)}};this.on=function(b,f,c){if(!e(this,"on",b,[f,c])||!f)return this;this._events||(this._events={});(this._events[b]||(this._events[b]=[])).push({callback:f,context:c,ctx:c||this});return this};this.off=function(b,f,c){var a,k,h,d,g,n,l,t;if(!this._events||!e(this,"off",
b,[f,c]))return this;if(!b&&!f&&!c)return this._events=void 0,this;d=b?[b]:p.keys(this._events);g=0;for(n=d.length;g<n;g++)if(b=d[g],h=this._events[b]){this._events[b]=a=[];if(f||c)for(l=0,t=h.length;l<t;l++)k=h[l],(f&&f!==k.callback&&f!==k.callback._callback||c&&c!==k.context)&&a.push(k);a.length||delete this._events[b]}return this};this.once=function(b,f,c){var a=this,e=function(){var h=l.call(arguments);f.apply(this,h);a.off(b,e,c)};this.on(b,e,c);return this};this.trigger=function(b){if(!this._events)return this;
var f=l.call(arguments,1);if(!e(this,"trigger",b,f))return this;var c=this._events[b],a=this._events.all;c&&k(c,f);a&&k(a,arguments);return this}}var l=Array.prototype.slice,p={isPlainObject:function(g){if("[object Object]"!==String(g)||g.nodeType||g.window&&g.window==g)return!1;try{if(g.constructor&&!g.constructor.prototype.hasOwnProperty("isPrototypeOf"))return!1}catch(e){return!1}return!0},keys:function(g){if(!this.isPlainObject(g))return[];var e=[],k;for(k in g)has(g,k)&&e.push(k);return e},_idCounter:0,
uniqueId:function(g){var e=++this._idCounter+"";return g?g+e:e}};return{create:function(){return new g}}});
extole.define("https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/logger.js",[],function(){function g(c,a,g){g=g||{};g.pageId=n;g.referer=e;var h;try{h=[a||"no message","START_JSON",JSON.stringify(g),"END_JSON"].join(" ")}catch(d){p("Failed to stringify log's json data",{exception:d});return}extole.LOG_EXCLUDE_REGEX&&h.match(extole.LOG_EXCLUDE_REGEX)||(f[h]=++f[h]||1,k[c]>=k[extole.LOG_LEVEL_CONSOLE]&&window.console&&window.console.log&&window.console.log(c+" "+h),k[c]>=
k[extole.LOG_LEVEL_REMOTE]&&(a=f[h],b[a]&&l(c,h+(1<a?" log count: "+a:""))))}function l(b,a){extole.require(["https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/api.js"],function(f){f.post("/api/v4/debug/logs",{level:b,message:a})})}function p(b,a){g("ERROR",b,a)}var n=String((new Date).getTime()),e=window.location.href,k={DEBUG:0,INFO:1,WARN:2,ERROR:3,OFF:4},b={1:!0,3:!0,10:!0,30:!0,100:!0,250:!0,500:!0,1E3:!0};extole.LOG_EXCLUDE_REGEX=extole.LOG_EXCLUDE_REGEX||void 0;
extole.LOG_LEVEL_CONSOLE=extole.LOG_LEVEL_CONSOLE||"OFF";extole.LOG_LEVEL_REMOTE=extole.LOG_LEVEL_REMOTE||"WARN";var f={};return{debug:function(b,a){g("DEBUG",b,a)},info:function(b,a){g("INFO",b,a)},warn:function(b,a){g("WARN",b,a)},error:p,LOGGING_ENDPOINT:"/api/v4/debug/logs"}});
extole.define("https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/Timer.js",[],function(){return function(){var g=this,l;this.start=function(){if(l)throw Error("Timer.start has already been called");l=new Date;return g};this.getElapsedTime=function(){if(!l)throw Error("Timer has not been started");return new Date-l}}});
extole.define("https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/type.js",[],function(){var g=function(g,n){return function(e){return l(g,e,n)}},l=function(g,l,e){e=e||{};g=Object.prototype.toString.call(l)==="[object "+g+"]";l=l&&e.construct?l.constructor===e.construct:!0;return(e.negate?!g:g)&&l};return{isPlainObject:g("Object",{construct:Object}),isPlainFunction:g("Function"),isArray:g("Array"),isString:g("String"),isBoolean:g("Boolean"),isUndefined:g("Undefined"),
isDefined:g("Undefined",{negate:!0}),isNull:g("Null"),test:l}});
extole.define("https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/uri.js",[],function(){function g(g){var l={};(function k(b,f){for(var c in b){var a=b[c],g=(f?f+".":"")+c;"[object Object]"===Object.prototype.toString.call(a)?k(a,g):l[g]=a}})(g);return l}function l(g){try{return decodeURIComponent(g)}catch(l){return g}}return{serialize:function(g){var l="",e;for(e in g)l+="&"+encodeURIComponent(e)+"="+encodeURIComponent(String(g[e]));return l.replace(/^\&/,"?")},deserialize:function(g){var n=
{};if(!g)return n;g=(g.match(/^\?/)?g.slice(1):g).split("&");for(var e=0;e<g.length;e++){var k=g[e].split("=");n[l(k[0])]=l(k[1])}return n},objectToDotNotation:g,dotNotationToObject:function(l){var n={};l=g(l);for(var e in l){for(var k=n,b=e.split("."),f=b.pop();b.length;)var c=b.shift(),k=k[c]=k[c]||{};k[f]=l[e]}return n},decodeComponent:l,encodeComponent:function(g){return encodeURIComponent(g)}}});
extole.define("https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/ajax.js",["https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/collection.js","https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/uri.js","https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/type.js","https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/logger.js"],function(g,l,p,n){var e=
[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Msxml2.XMLHTTP")},function(){return new ActiveXObject("Msxml3.XMLHTTP")},function(){return new ActiveXObject("Microsoft.XMLHTTP")}],k=function(b,f){var c=Array.prototype.slice.call(arguments),a=f.headers||{},e=f.xhrFields||{},h=f.url||"",d=f.data||"",k=(f.type||"get").toUpperCase(),v=f.complete||function(){},u=f.error||function(){n.error("Error with url "+h+"= "+c.join(","))};p.isPlainObject(d)&&("GET"==k?(h+=l.serialize(d),
d=null):d=JSON.stringify(d));b.open(k,h,!0);g.merge(b,e);g.each(a,function(a,d){try{b.setRequestHeader(d,a)}catch(c){n.error("AJAX ERROR: Couldn't set request header "+d+" to "+a)}});var t=!1;b.onerror=function(a){t||(t=!0,u.call(b,b.statusText,b.status))};a=function(){void 0!==b.readyState&&4!==b.readyState||t||(t=!0,String(b.status||200).match(/^[23]/)?"function"===typeof v?v.call(b,b.responseText,b):n.warn("`complete` callback must be a function."):u.call(b,b.statusText,b.status))};b.onload=a;
b.onreadystatechange=a;b.send(d)};return function(b){b=b||{};var f;f=!1;for(var c=0;c<e.length;c++){try{f=e[c]()}catch(a){continue}break}k(f,b);return f}});
extole.define("https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/client/program.js",[],function(){return{getName:function(){return extole.PROGRAM.name},getProgramDomain:function(){return extole.PROGRAM.programDomain},getSitePatterns:function(){return extole.PROGRAM.sitePatterns},isSecure:function(){return Boolean(extole.PROGRAM.isSecure)},getProtocol:function(){return this.isSecure()?"https://":window.location.protocol.match(/^https/)?"https://":"http://"}}});
extole.define("https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/client/token-store.js",["https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/collection.js","https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/logger.js","https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/event-bus.js","https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/cookie.js",
"https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/client/program.js"],function(g,l,p,n,e){function k(){function f(){this.get=function(a){return n(a)};this.set=function(a,d,c){extole.COOKIES_DISABLED||n(a,d,{expires:b[c],path:"/",secure:e.isSecure()})};this.remove=function(a){n(a,"",{expires:-1,path:"/"})}}function c(){(function(){var a="test"+(new Date).getTime();try{localStorage.setItem(a,a),localStorage.removeItem(a)}catch(b){throw Error("Local storage not supported");
}})();this.get=function(a){return window.localStorage.getItem(a)};this.set=function(a,b,c){window.localStorage.setItem(a,b)};this.remove=function(a){window.localStorage.removeItem(a)}}var a=[],k=extole.CORE_CONFIG.cookieConsentEnabled?"SESSION":"YEAR";a.push(new function(){var a={};this.get=function(b){return a[b]};this.set=function(b,c,f){a[b]=c};this.remove=function(b){delete a[b]}});extole.COOKIES_DISABLED||a.push(new f);if(extole.LOCAL_STORAGE_ENABLED)try{a.push(new c)}catch(h){l.info("Local Storage not supported in current browser")}this.events=
p.create();this.get=function(){for(var b,d=0;d<a.length;d++){b=a[d];var c=b.get("extole_access_token");if(Boolean("string"===typeof c&&"undefined"!==c&&"null"!==c&&c.length))return b.get("extole_access_token")}return null};this.set=function(b,d){var c=this.get();k=d||k;g.each(a,function(a){a.set("extole_access_token",b,k)});c!==b&&this.events.trigger("change:access_token");c&&c!=b&&l.debug("ACCESS_TOKEN_CHANGE - the access token changed from: "+c+", to: "+b)};this.remove=function(){g.each(a,function(a){a.remove("extole_access_token")})}}
var b={year:365,YEAR:365,session:null,SESSION:null};return extole.tokenStore=extole.tokenStore?extole.tokenStore:new k});
extole.define("CreativeRenderContext",["https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/uri.js","https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/collection.js"],function(g,l){function p(e,b,f){this.getElement=function(){return f};this.getName=function(){return e};this.getData=function(){return b};this.getParameters=function(){return b}}function n(){this.getName=function(){return extole.PROGRAM.name};this.getProgramDomain=function(){return extole.PROGRAM.programDomain};
this.getSitePatterns=function(){return extole.PROGRAM.sitePatterns}}function e(){this.backendTargetingEnabled=function(){return!0};this.cookieConsentEnabled=function(){return extole.CORE_CONFIG.cookieConsentEnabled}}return function(k,b,f,c){var a=new p(k,b,f),q=new n,h=new e;this.getZone=function(){return a};this.getProgram=function(){return q};this.getCreativeData=function(){var b=g.dotNotationToObject(g.deserialize(location.search)),c=g.dotNotationToObject(a.getParameters());return l.merge(b.extole_creative,
c.creative)};this.getCoreConfig=function(){return h};this.getLocale=function(){return c||null}}});
extole.define("find-element-by-id",["https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/logger.js"],function(g){function l(g,l,e){function k(){if(l())e();else{g();var f=setTimeout,c;b||(b=10);c=500<b?500:b*=1.1;f(k,c)}}var b;k()}return function(p,n){var e=(new Date).getTime(),k=!1,b;l(function(){b=document.getElementById(p)},function(){var f=(new Date).getTime()-e;!k&&5E3<f&&(k=!0,g.info("Scanned for 5000 ms searching for zone element id: "+p));return Boolean(b)},function(){n(b)})}});
extole.define("pending-zone-service",["find-element-by-id","https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/logger.js","https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/collection.js","https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/client/token-store.js","CreativeRenderContext"],function(g,l,p,n,e){function k(a,b){a.element?b(a.element):a.element_id?g(a.element_id,b):b(document.body.appendChild(document.createElement("DIV")))}
function b(a){a=p.merge({},a);delete a.campaign_id;delete a.extole_campaign_id;return a}var f={},c=function(a,c){c=c||function(){};var f=a.name,d=b(a.data||a.parameters||{});this.resolve=function(b,g,l,p){n.set(g,l);k(a,function(a){a=new e(f,d,a,p);b(a);c(null,a.getZone())})}};return{get:function(a){if(!f[a])throw Error("Pending zone does not exist for id: "+a);return f[a]},create:function(){var a=Math.floor(1E9*Math.random()),b=0;return function(e,d){b++;var g=a+"."+b;f[g]=new c(e,d);return g}}()}});
extole.define("create-zone","https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/uri.js https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/collection.js https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/type.js https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/dom.js https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/client/program.js https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/client/token-store.js https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/ajax.js https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/logger.js pending-zone-service".split(" "),
function(g,l,p,n,e,k,b,f,c){function a(a){var b=document.createElement("script");n.setAttribute(b,"src",a);n.setAttribute(b,"async","");n.append(n.query("head")[0],b);return b}return function(n,h,d){function p(a,c,d,e){m=a+"/zones";a={"Content-Type":"application/x-www-form-urlencoded",Accept:"text/javascript","X-Extole-App":"javascript_sdk"};t&&(a.Authorization="Bearer+"+t);var g=function(a,b,c){var d=[];l.each(a,function(b,c){"Content-Type"!==c&&(d.push("::headers."+c+"="+b),delete a[c])});l.each(c,
function(a,b){b=window.encodeURIComponent(b);b=-1<b.indexOf(".")?'"'+b+'"':b;a=window.encodeURIComponent(a);d.push("data."+b+"="+a)});d.push("event_name="+b);return d.join("&")}(a,c.name,d);b({url:m,type:"POST",headers:a,data:g,complete:function(a,b){var c=b.getResponseHeader("Content-Type");if("text/javascript"===c)try{(new Function(a))()}catch(d){f.error("Error in zone script retrieved from "+m+" - MESSAGE: "+d.message+" STACK: "+d.stack)}else"text/plain"!==c||a?f.error("Invalid content type returned from "+
m+": "+c+" Zone Request Data: "+g):f.info("No campaign targeted in POST to /zones - Zone Request Data: "+g);e()},error:function(a){f.error("Error creating zone via POST to "+m,a)},xhrFields:{withCredentials:!0}})}function v(){"function"===typeof d&&setTimeout(d,500)}h=h||function(){};var u=l.flatten(n.data||n.parameters||{});u.zone_id=c.create(n,h);var t=k.get();h=[e.getProtocol(),e.getProgramDomain()].join("");var m;extole.ZONE_POST?p(h,n,u,v):(t&&(u.access_token=t),u.extole_app="javascript_sdk",
m=[h,"/zones/",n.name].join(""),a(m+g.serialize(u)).onload=v)}});
extole.define("create-zone-executor",["create-zone","https://origin.xtlo.net/type=core:clientId=2035193665:coreAssetsVersion=19/common/logger.js"],function(g,l){function p(e){var b=!1;return function(){var f=Array.prototype.slice.call(arguments);b||(b=!0,e.apply(null,f))}}var n=new function(){var e=0,b=[],f=this;this.push=function(c){b.push(c);this.next()};this.next=function(){for(var c=function(){e--;f.next()};1>e&&b.length;)b.shift()(c),e++}},e=0;return{execute:function(k,b){b=b||function(){};-1!==
["conversion","confirmation"].indexOf(k.name)&&l.info("CRITICAL_ZONE_REQUEST - ### "+JSON.stringify(k)+" ###");0===e?n.push(function(e){e=p(e);g(k,function(){var c=Array.prototype.slice.call(arguments);b.apply(null,c);e()},e)}):n.push(function(e){g(k,b);e()});e++}}});